////////////////////////////////////////////////////////////////////////
//
// AltovaException.cpp
//
// This file was generated by XMLSpy 2005 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#include "Altova.h"
#include "SchemaTypes.h"
#include "AltovaException.h"

namespace altova {


CAltovaException::CAltovaException(int nCode, const tstring& sMessage)
	: m_nCode(nCode), m_sMessage(sMessage)
{
}


int CAltovaException::GetCode()
{
	return m_nCode;
}


tstring CAltovaException::GetInfo()
{
	return m_sMessage;
}


} // namespace altova
