#-------------------------------------------------------------------------
#	FaultInjectionXML
#
#	
#
#	GENERATION BY XMLSPY2005 
#
#	HollySys Copyright (C) 2005-2008
#-------------------------------------------------------------------------

libFaultInjectionXML.so:FaultInjectionXML.o
	g++ -g -shared -o ../../../PublicProject/Debug/bin/libFaultInjectionXML.so Debug/FaultInjectionXML.o
	
FaultInjectionXML.o:FaultInjectionXML.h FaultInjectionXML.cpp 
	g++ -c -g -o Debug/FaultInjectionXML.o FaultInjectionXML.cpp