#-------------------------------------------------------------------------
#	AltovaXML_Dll_Xerces_nomfc
#
#	2007-9-17 ZhibingHong
#
#	AltovaXML_Dll_Xerces_nomfc模块在Linux下编译Make文件
#
#	HollySys Copyright (C) 2005-2008
#-------------------------------------------------------------------------

libAltovaXML_Dll_Xerces_nomfc.so:Doc.o Node.o XmlException.o OS_Ext.o
	g++ -g -shared -o ../../../PublicProject/Debug/bin/libAltovaXML_Dll_Xerces_nomfc.so Debug/Doc.o Debug/Node.o Debug/XmlException.o Debug/OS_Ext.o
	
Doc.o:Doc.h Doc.cpp XmlException.h Node.h
	g++ -c -g -o Debug/Doc.o Doc.cpp

Node.o:Node.h Node.cpp XmlException.h Doc.h
	g++ -c -g -o Debug/Node.o Node.cpp
	
XmlException.o:XmlException.h XmlException.cpp
	g++ -c -g -o Debug/XmlException.o XmlException.cpp
	
OS_Ext.o:../../../OORTDB_Design/Server/PublicFile/OS_Ext/OS_Ext.h ../../../OORTDB_Design/Server/PublicFile/OS_Ext/OS_Ext.cpp
	g++ -c -g -o Debug/OS_Ext.o ../../../OORTDB_Design/Server/PublicFile/OS_Ext/OS_Ext.cpp